### ISSUE TITLE
Live dashboard: Use packages.json as the source of information

### ISSUE THREAD

**Issue by HenrikBengtsson** [cranhaven/cranhaven.org#7]
The <https://github.com/cranhaven/cranhaven.r-universe.dev/blob/main/packages.json> could be made the main source of information for the live dashboard. If it's not there, it's not relevant.

For example, we already have fields like `on_cran` (always false), and `archived_on`;

```json
  {
    "package": "ffsimulator",
    "on_cran": false,
    "archived_on": "2024-02-27 06:02:00",
    "url": "https://github.com/cranhaven/cranhaven.r-universe.dev",
    "branch": "package/ffsimulator",
    "subdir": "ffsimulator"
  },
```

We could include the PACKAGES.in information in this file too, e.g.

```sh
Package: ffsimulator
X-CRAN-History: Archived on 2023-01-10 as requires archived package 'ffscrapr'.
  Unarchived on 2023-02-12.
X-CRAN-Comment: Archived on 2024-02-27 as issues were not corrected in time.
```

Maybe something like:

```json
 {
    "package": "ffsimulator",
    "url": "https://github.com/cranhaven/cranhaven.r-universe.dev",
    "branch": "package/ffsimulator",
    "subdir": "ffsimulator"
    "on_cran": false,
    "events": [
       [ "date": "2024-01-10", "event": "archived",   "reason": "requires archived package 'ffscrapr'" ],
       [ "date": "2024-02-12", "event": "unarchived", "reason": "" ],
       [ "date": "2024-02-27", "event": "archived",   "reason": "issues were not corrected in time" ]
    ]
  },
```

The obvious advantage would be to make sure that the dashboard and the actual content on CRANhaven is the same, e.g. changing the time limit, if there's a bug in one or the other, ... It will also make it more clear what data sources we are using, i.e. fewer scripts to look at to figure that out.

**Comment by llrs** [comment]
I agree with unifying the data sources

Sorry it took time to answer on this: I thought that initially the data came from the cran.r-universe.org, and I wanted to double check the update.R code. 

I am not sure that github.com/cran is the right place to pull the code https://github.com/cranhaven/cranhaven.r-universe.dev/blob/14638e428abe6b6baa65277916f70f3480467883/update.R#L75. 
I've heard cases when CRAN team modifies a package without changing the version number. 
Is this picked by the bot that feeds it? 
If it indeed works well, we could just point the cranhaven universe to use the latest version on github.com/cran/<pkg> instead of creating a new branch for each package...

Before adding more data to the json (+1) maybe we need to check the r-universe documentation first.
I am not sure the json can have other data or if some new fields might interfere with it.

**Comment by HenrikBengtsson** [comment]
> If it indeed works well, we could just point the cranhaven universe to use the latest version on [github.com/cran/](http://github.com/cran/) instead of creating a new branch for each package...

I did that in the first iteration, but I found I had to add CRANhaven to `Additional_repositories` so that packages that were archived because they depend on another archived package would build on R-universe.  Without it, they failed to build because the dependency was not available.  I don't think there's a way to tell R-universe to use CRANhaven as a package repository, cf. https://github.com/r-universe-org/help?tab=readme-ov-file#is-it-possible-to-customize-the-package-build-process-with-custom-optionstoolsvariables.

**Comment by HenrikBengtsson** [comment]
>  I am not sure the json can have other data or if some new fields might interfere with it.

Note that there's already two custom non-R-universe fields (`on_cran`, and `archived_on`) that's been there since almost the start; haven't noticed any issues.

**Comment by HenrikBengtsson** [comment]
I've made some first steps towards this, cf. https://github.com/cranhaven/cranhaven.r-universe.dev/commit/0c630b40bed57fbca9c6f279614cdb19eb9ce6a5. The [packages.json](https://github.com/cranhaven/cranhaven.r-universe.dev/blob/main/packages.json) file now has annotations from PACKAGES.in.

**Comment by HenrikBengtsson** [comment]
This is now completed.
